version: 2

project_name: cloudfront-tenant-operator
dist: .goreleaser-dist

builds:
  - id: manager
    main: ./cmd/main.go
    binary: manager
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

dockers_v2:
  - images:
      - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_REPO }}"
    dockerfile: Dockerfile.release
    tags:
      - "{{ .Version }}"
      - latest
    sbom: false
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.source": "{{ .GitURL }}"

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  use: github-native

release:
  prerelease: auto
