//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateCustomization) DeepCopyInto(out *CertificateCustomization) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateCustomization.
func (in *CertificateCustomization) DeepCopy() *CertificateCustomization {
	if in == nil {
		return nil
	}
	out := new(CertificateCustomization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Customizations) DeepCopyInto(out *Customizations) {
	*out = *in
	if in.WebAcl != nil {
		in, out := &in.WebAcl, &out.WebAcl
		*out = new(WebAclCustomization)
		(*in).DeepCopyInto(*out)
	}
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(CertificateCustomization)
		**out = **in
	}
	if in.GeoRestrictions != nil {
		in, out := &in.GeoRestrictions, &out.GeoRestrictions
		*out = new(GeoRestrictionCustomization)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Customizations.
func (in *Customizations) DeepCopy() *Customizations {
	if in == nil {
		return nil
	}
	out := new(Customizations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSConfig) DeepCopyInto(out *DNSConfig) {
	*out = *in
	if in.HostedZoneId != nil {
		in, out := &in.HostedZoneId, &out.HostedZoneId
		*out = new(string)
		**out = **in
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(int64)
		**out = **in
	}
	if in.AssumeRoleArn != nil {
		in, out := &in.AssumeRoleArn, &out.AssumeRoleArn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSConfig.
func (in *DNSConfig) DeepCopy() *DNSConfig {
	if in == nil {
		return nil
	}
	out := new(DNSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributionTenant) DeepCopyInto(out *DistributionTenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributionTenant.
func (in *DistributionTenant) DeepCopy() *DistributionTenant {
	if in == nil {
		return nil
	}
	out := new(DistributionTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DistributionTenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributionTenantList) DeepCopyInto(out *DistributionTenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DistributionTenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributionTenantList.
func (in *DistributionTenantList) DeepCopy() *DistributionTenantList {
	if in == nil {
		return nil
	}
	out := new(DistributionTenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DistributionTenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributionTenantSpec) DeepCopyInto(out *DistributionTenantSpec) {
	*out = *in
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]DomainSpec, len(*in))
		copy(*out, *in)
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ConnectionGroupId != nil {
		in, out := &in.ConnectionGroupId, &out.ConnectionGroupId
		*out = new(string)
		**out = **in
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]Parameter, len(*in))
		copy(*out, *in)
	}
	if in.Customizations != nil {
		in, out := &in.Customizations, &out.Customizations
		*out = new(Customizations)
		(*in).DeepCopyInto(*out)
	}
	if in.ManagedCertificateRequest != nil {
		in, out := &in.ManagedCertificateRequest, &out.ManagedCertificateRequest
		*out = new(ManagedCertificateRequest)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]Tag, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = new(DNSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributionTenantSpec.
func (in *DistributionTenantSpec) DeepCopy() *DistributionTenantSpec {
	if in == nil {
		return nil
	}
	out := new(DistributionTenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributionTenantStatus) DeepCopyInto(out *DistributionTenantStatus) {
	*out = *in
	if in.CreatedTime != nil {
		in, out := &in.CreatedTime, &out.CreatedTime
		*out = (*in).DeepCopy()
	}
	if in.LastModifiedTime != nil {
		in, out := &in.LastModifiedTime, &out.LastModifiedTime
		*out = (*in).DeepCopy()
	}
	if in.DomainResults != nil {
		in, out := &in.DomainResults, &out.DomainResults
		*out = make([]DomainResult, len(*in))
		copy(*out, *in)
	}
	if in.LastDriftCheckTime != nil {
		in, out := &in.LastDriftCheckTime, &out.LastDriftCheckTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributionTenantStatus.
func (in *DistributionTenantStatus) DeepCopy() *DistributionTenantStatus {
	if in == nil {
		return nil
	}
	out := new(DistributionTenantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainResult) DeepCopyInto(out *DomainResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainResult.
func (in *DomainResult) DeepCopy() *DomainResult {
	if in == nil {
		return nil
	}
	out := new(DomainResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainSpec) DeepCopyInto(out *DomainSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainSpec.
func (in *DomainSpec) DeepCopy() *DomainSpec {
	if in == nil {
		return nil
	}
	out := new(DomainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoDBSourceConfig) DeepCopyInto(out *DynamoDBSourceConfig) {
	*out = *in
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.NameAttribute != nil {
		in, out := &in.NameAttribute, &out.NameAttribute
		*out = new(string)
		**out = **in
	}
	if in.DomainAttribute != nil {
		in, out := &in.DomainAttribute, &out.DomainAttribute
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoDBSourceConfig.
func (in *DynamoDBSourceConfig) DeepCopy() *DynamoDBSourceConfig {
	if in == nil {
		return nil
	}
	out := new(DynamoDBSourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeoRestrictionCustomization) DeepCopyInto(out *GeoRestrictionCustomization) {
	*out = *in
	if in.Locations != nil {
		in, out := &in.Locations, &out.Locations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeoRestrictionCustomization.
func (in *GeoRestrictionCustomization) DeepCopy() *GeoRestrictionCustomization {
	if in == nil {
		return nil
	}
	out := new(GeoRestrictionCustomization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedCertificateRequest) DeepCopyInto(out *ManagedCertificateRequest) {
	*out = *in
	if in.CertificateTransparencyLoggingPreference != nil {
		in, out := &in.CertificateTransparencyLoggingPreference, &out.CertificateTransparencyLoggingPreference
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedCertificateRequest.
func (in *ManagedCertificateRequest) DeepCopy() *ManagedCertificateRequest {
	if in == nil {
		return nil
	}
	out := new(ManagedCertificateRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Parameter) DeepCopyInto(out *Parameter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Parameter.
func (in *Parameter) DeepCopy() *Parameter {
	if in == nil {
		return nil
	}
	out := new(Parameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PendingChange) DeepCopyInto(out *PendingChange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PendingChange.
func (in *PendingChange) DeepCopy() *PendingChange {
	if in == nil {
		return nil
	}
	out := new(PendingChange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresSourceConfig) DeepCopyInto(out *PostgresSourceConfig) {
	*out = *in
	out.ConnectionSecretRef = in.ConnectionSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresSourceConfig.
func (in *PostgresSourceConfig) DeepCopy() *PostgresSourceConfig {
	if in == nil {
		return nil
	}
	out := new(PostgresSourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tag) DeepCopyInto(out *Tag) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tag.
func (in *Tag) DeepCopy() *Tag {
	if in == nil {
		return nil
	}
	out := new(Tag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantSource) DeepCopyInto(out *TenantSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantSource.
func (in *TenantSource) DeepCopy() *TenantSource {
	if in == nil {
		return nil
	}
	out := new(TenantSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantSourceList) DeepCopyInto(out *TenantSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TenantSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantSourceList.
func (in *TenantSourceList) DeepCopy() *TenantSourceList {
	if in == nil {
		return nil
	}
	out := new(TenantSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantSourceSpec) DeepCopyInto(out *TenantSourceSpec) {
	*out = *in
	if in.PollInterval != nil {
		in, out := &in.PollInterval, &out.PollInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Postgres != nil {
		in, out := &in.Postgres, &out.Postgres
		*out = new(PostgresSourceConfig)
		**out = **in
	}
	if in.DynamoDB != nil {
		in, out := &in.DynamoDB, &out.DynamoDB
		*out = new(DynamoDBSourceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetNamespace != nil {
		in, out := &in.TargetNamespace, &out.TargetNamespace
		*out = new(string)
		**out = **in
	}
	if in.DryRun != nil {
		in, out := &in.DryRun, &out.DryRun
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantSourceSpec.
func (in *TenantSourceSpec) DeepCopy() *TenantSourceSpec {
	if in == nil {
		return nil
	}
	out := new(TenantSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantSourceStatus) DeepCopyInto(out *TenantSourceStatus) {
	*out = *in
	if in.LastPollTime != nil {
		in, out := &in.LastPollTime, &out.LastPollTime
		*out = (*in).DeepCopy()
	}
	if in.PendingChanges != nil {
		in, out := &in.PendingChanges, &out.PendingChanges
		*out = make([]PendingChange, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantSourceStatus.
func (in *TenantSourceStatus) DeepCopy() *TenantSourceStatus {
	if in == nil {
		return nil
	}
	out := new(TenantSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebAclCustomization) DeepCopyInto(out *WebAclCustomization) {
	*out = *in
	if in.Arn != nil {
		in, out := &in.Arn, &out.Arn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebAclCustomization.
func (in *WebAclCustomization) DeepCopy() *WebAclCustomization {
	if in == nil {
		return nil
	}
	out := new(WebAclCustomization)
	in.DeepCopyInto(out)
	return out
}
